name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '18'
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: cargo clippy
        run: |
          cargo clippy --all-features --all-targets --workspace -- -D warnings
      - name: cargo test
        run: |
          cargo test --workspace
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install & Build
        run: |
          npm install
          npm run release-build
          rm ./public/pkg/.gitignore
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public
